[global.limits]

[development]
address = "localhost"
port = 8000
workers = 1
keep_alive = 5
log = "normal"

[production]
address = "127.0.0.1"
port = 8414
workers = 12
keep_alive = 5
log = "critical"
# secret_key = ""
